language: python
python:
  - "2.7"
  #- "3.4"
addons:
    apt:
        sources: 
            - atlas
            - opencv
        packages: 
            - python-opencv
            - cmake
            #- opencv
            #- atlas
            #- libatlas-dev
before_install:
  - mkdir $HOME/code
  - cd $HOME/code
  - git clone -b next https://github.com/Erotemic/utool.git
  - cd utool
  - python setup.py develop
  - cd $HOME/build/Erotemic/vtool
  - pip install numpy
  - pip install scipy
  - pip install cython
  - pip install scikit-learn
  - pip install statsmodels
install:
  - python setup.py build develop
script: 
  - travis_wait ./run_tests.py
after_failure: 
  - cat failed_doctests.txt
cache: 
    directories:
        - $HOME/code
        - $HOME/code/utool
        - $HOME/.pip-cache/
    apt
