language: python
python:
  - "2.7"
  #- "3.4"
addons:
    apt:
        packages: 
            - python-opencv
before_install:
  - mkdir ~/code
  - cd ~/code
  - git clone -b next https://github.com/Erotemic/utool.git
  - cd ~/code/utool
  - python setup.py develop
  - echo done
install:
  - travis_retry python setup.py build develop
script: 
  - travis_wait ./run_tests.py
after_failure: 
  - cat failed_doctests.txt
#cache: 
#    apt
