language: python

sudo: false

python:
  - "2.7"
  #- "3.4"
addons:
# https://github.com/travis-ci/apt-source-whitelist#source-approval-process
    apt:
        #sources: 
        #    #- atlas
        #    - libatlas-dev
        #    - opencv
        packages: 
            - cmake
            - python-opencv
            - libatlas3gf-base
            - libatlas-dev
            - libblas-dev
            - python-scipy
            #- libatlas-dev
before_install:
  - mkdir -p $HOME/code
  - cd $HOME/code
  - git clone -b next https://github.com/Erotemic/utool.git
  - cd utool
  - git pull
  - python setup.py develop
  - cd $HOME/build/Erotemic/vtool
  - pip install numpy
  - pip install scipy
  - pip install cython
  - pip install scikit-learn
  - pip install statsmodels
install:
  - python setup.py build develop
script: 
  - travis_wait ./run_tests.py
after_failure: 
  - cat failed_doctests.txt
cache: 
    apt: true
    directories:
        - $HOME/code
        - $HOME/code/utool
        - $HOME/.pip-cache
        #apt
