language: python
python:
  - "2.7"
  #- "3.4"
addons:
    apt:
        packages: 
            - python-opencv
            - cmake
            - opencv
before_install:
  #- mkdir ~/code
  #- cd ~/code
  - git clone -b next https://github.com/Erotemic/utool.git
  #- cd ~/code/utool
  - cd utool
  - python setup.py develop
  - cd ..
  - pwd
install:
  - python setup.py build develop
script: 
  - travis_wait ./run_tests.py
after_failure: 
  - cat failed_doctests.txt
cache: 
    apt
